# config/doctrine.yaml
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%env(DB_HOST)%'
        dbname: '%env(DB_NAME)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASS)%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Arc:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Models'
                prefix: 'Src\Models'
                alias: Src
